INSERT INTO pla_project (prj_id, prj_code, prj_name, prj_desc, prj_status, prj_prg_id, prj_prj_id, "version")
VALUES
( 1, 'PA1', 'EXTENSION DU RÉSEAU DES LIEUX CULTUELS ET CULTURELS', 'EXTENSION DU RÉSEAU DES LIEUX CULTUELS ET CULTURELS', '', 1, null, 0),
( 2, 'PA2', 'MAINTENANCE ET AMÉLIORATION DE LA QUALITÉ DES LIEUX CULTUELS ET CULTURELS', 'MAINTENANCE ET AMÉLIORATION DE LA QUALITÉ DES LIEUX CULTUELS ET CULTURELS', '', 1, null, 0),
( 3, 'PA3', 'CONSERVATION DES LIEUX CULTUELS ET CULTURELS HISTORIQUES', 'CONSERVATION DES LIEUX CULTUELS ET CULTURELS HISTORIQUES', '', 1, null, 0),
( 4, 'PA4', 'SOUTIEN DES MISSIONS', 'SOUTIEN DES MISSIONS', '', 1, null, 0);





