INSERT INTO pla_project (prj_id, prj_code, prj_name, prj_desc, prj_status, prj_prg_id, prj_prj_id, "version")
VALUES
( 11, 'SPA11', 'CONSTRUCTION ET AMÉNAGEMENT DES MOSQUÉES ET DE LEURS DÉPENDANCES ET DES MSSALA', 'CONSTRUCTION ET AMÉNAGEMENT DES MOSQUÉES ET DE LEURS DÉPENDANCES ET DES MSSALA', '', 1, 1, 0),
( 21, 'SPA21', 'MISE À NIVEAU DES MOSQUÉES', 'MISE À NIVEAU DES MOSQUÉES', '', 1, 2, 0),
( 22, 'SPA22', 'EQUIPEMENT DES MOSQUÉES ET DE LEURS DÉPENDANCES ET DES MSALLAS', 'EQUIPEMENT DES MOSQUÉES ET DE LEURS DÉPENDANCES ET DES MSALLAS', '', 1, 2, 0),
( 23, 'SPA23', 'PROTECTION DES MOSQUÉES CONTRE LES INCENDIES ET LA PANIQUE', 'PROTECTION DES MOSQUÉES CONTRE LES INCENDIES ET LA PANIQUE', '', 1, 2, 0),
( 24, 'SPA24', 'EFFICACITÉ ÉNERGITIQUE DANS LES MOSQUÉES', 'EFFICACITÉ ÉNERGITIQUE DANS LES MOSQUÉES', '', 1, 2, 0),
( 25, 'SPA25', 'APPROVISIONNEMENT EN EAU POTABLE ET ASSAINISSEMENT DES ÉCOLES RURALES, DES ÉCOLES DE L''ENSEIGNEMENT TRADITIONNEL ET DES MOSQUÉES', 'APPROVISIONNEMENT EN EAU POTABLE ET ASSAINISSEMENT DES ÉCOLES RURALES, DES ÉCOLES DE L''ENSEIGNEMENT TRADITIONNEL ET DES MOSQUÉES', '', 1, 2, 0),
( 26, 'SPA26', 'GÉNÉRALISATION DU BRANCHEMENT DES MOSQUÉES EN ÉLECTRICITÉ, EN EAU POTABLE ET EN ASSAINISSEMENT', 'GÉNÉRALISATION DU BRANCHEMENT DES MOSQUÉES EN ÉLECTRICITÉ, EN EAU POTABLE ET EN ASSAINISSEMENT', '', 1, 2, 0),
( 27, 'SPA27', 'MAINTENANCE ET DE GESTION DES MOSQUÉES ET DE LEURS DÉPENDANCES', 'MAINTENANCE ET DE GESTION DES MOSQUÉES ET DE LEURS DÉPENDANCES', '', 1, 2, 0),
( 31, 'SPA31', 'CONSERVATION DES MOSQUÉES HISTORIQUES', 'CONSERVATION DES MOSQUÉES HISTORIQUES', '', 1, 3, 0),
( 41, 'SPA41', 'SOUTIEN DES MISSIONS', 'SOUTIEN DES MISSIONS', '', 1, 4, 0);










