ALTER TABLE MON_NE_SUBDEVICE ADD NSD_PRO_ID NUMBER(19);
ALTER TABLE MON_NE_SUBDEVICE ADD NSD_VAL_ID NUMBER(19);
ALTER TABLE MON_NE_SUBDEVICE ADD NSD_NSD_ID NUMBER(19);

-- Reference from MonNeSubdevice.nsdProId to MonXfsProperty
ALTER TABLE MON_NE_SUBDEVICE ADD CONSTRAINT FK_MON_NE_SUBDEVICE_NSD_PRO_ID
	FOREIGN KEY (NSD_PRO_ID) REFERENCES MON_XFS_PROPERTY (PRO_ID);
CREATE INDEX IX_MON_NE_SUBDEVICE_NSD_PRO_ID ON MON_NE_SUBDEVICE (NSD_PRO_ID);

-- Reference from MonNeSubdevice.nsdValId to MonXfsValue
ALTER TABLE MON_NE_SUBDEVICE ADD CONSTRAINT FK_MON_NE_SUBDEVICE_NSD_VAL_ID
	FOREIGN KEY (NSD_VAL_ID) REFERENCES MON_XFS_VALUE (VAL_ID);
CREATE INDEX IX_MON_NE_SUBDEVICE_NSD_VAL_ID ON MON_NE_SUBDEVICE (NSD_VAL_ID);

-- Reference from MonNeSubdevice.nsdNsdId to MonNeSubdevice
ALTER TABLE MON_NE_SUBDEVICE ADD CONSTRAINT FK_MON_NE_SUBDEVICE_NSD_NSD_ID
	FOREIGN KEY (NSD_NSD_ID) REFERENCES MON_NE_SUBDEVICE (NSD_ID) ON DELETE CASCADE;
CREATE INDEX IX_MON_NE_SUBDEVICE_NSD_NSD_ID ON MON_NE_SUBDEVICE (NSD_NSD_ID);

