delete from  ejr_alimentation ;
delete from  ejr_arrete_central ;
delete from  ejr_arrete_gab ;
delete from  ejr_cash_counter ;
delete from  ejr_cash_counter_sop ;
delete from  ejr_cash_counter_cleared ;
delete from  ejr_file ;
delete from  ejr_lost_files ;
delete from  ejr_phy_cas ;
delete from  ejr_retract ;
delete from  ejr_transaction ;
delete from  ejr_server_cnx ;
delete from  ejr_device ;
delete from  ejr_coffre_event ;
delete from  ejr_wincor_error ;
delete from  ejr_cassette;
delete from  ejr_cas_notif;
delete from  ejr_count_clear;